import pandas as pd


# 1. Load data
if not os.path.exists(DATA_CSV):
raise FileNotFoundError(f"Data file not found: {DATA_CSV}")


df = pd.read_csv(DATA_CSV)


# 2. Calculate IT department frequency
it_count = int((df['department'] == 'IT').sum())


# 3. Print frequency
print(f"Number of employees in IT department: {it_count}")


# 4. Create histogram / bar chart of department distribution
plt.figure(figsize=(10,6))
sns.countplot(x='department', data=df)
plt.title('Distribution of Employees by Department')
plt.xlabel('Department')
plt.ylabel('Count')
plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig(PLOT_FILE)
plt.close()


print(f"Saved department distribution plot to {PLOT_FILE}")


# 5. Generate a simple index.html that embeds the image and shows IT count
html_content = f"""
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Employee Performance Analysis</title>
<style>
body {{ font-family: Arial, sans-serif; margin: 40px; }}
.card {{ border: 1px solid #ddd; padding: 20px; border-radius: 8px; max-width: 900px; }}
img {{ max-width: 100%; height: auto; }}
</style>
</head>
<body>
<div class="card">
<h1>Employee Performance Analysis</h1>
<p><strong>IT department employee count:</strong> {it_count}</p>
<h2>Department distribution</h2>
<p>The chart below shows the number of employees in each department (generated from <code>{DATA_CSV}</code>).</p>
<img src="{PLOT_FILE}" alt="Department distribution">
<hr>
<p>CSV data file included in the repository: <a href="{DATA_CSV}">{DATA_CSV}</a></p>
<p>Generated by script <code>emp-perf-analysis.py</code>.</p>
</div>
</body>
</html>
"""


with open(HTML_FILE, 'w', encoding='utf-8') as f:
f.write(html_content)


print(f"Saved HTML report to {HTML_FILE}")
